services:
  embedding:
    extends:
      file: docker-compose.yml
      service: embedding
    image: momoi-embedding:local
    build:
      context: .
      dockerfile: Dockerfile.embedding
  napcat:
    extends:
      file: docker-compose.yml
      service: napcat
  momoi:
    extends:
      file: docker-compose.yml
      service: momoi
    image: momoi:local
    build:
      context: .
      target: release

volumes:
  napcat-qq:
