<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Momoi</AssemblyName>
    <ApplicationIcon>Assets/momoi.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Momoi.Update/Momoi.Update.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
    <Resource Include="Assets/momoi.ico" />
  </ItemGroup>
</Project>
