REPLY_WAIT_FIRST_CHECK_SECONDS = 3 * 60
REPLY_WAIT_FINAL_CHECK_SECONDS = 10 * 60
REPLY_WAIT_FOLLOWUP_DELAY_SECONDS = (
    REPLY_WAIT_FINAL_CHECK_SECONDS - REPLY_WAIT_FIRST_CHECK_SECONDS
)
REPLY_WAIT_MAX_CHECKS = 2
