import asyncio
import logging
from typing import Any

from ...logging_context import log_event
from ...models import ToolCall
from ...text_replacement import cyber_keyword_pre_hook
from ..agent import AgentWorkflow
from ..context.presentation import heartbeat_self_state_lines
from ..context.rendering import recall_episode_context
from ..parsing import parse_reflection_finish
from ..protocol import REFLECTION_FINISH_SPEC
from ..turn_support import (
    REFLECTION_PROMPT_PATH,
    REFLECTION_SYSTEM_PROMPT,
    live_prompt as _live_prompt,
    pack_user_context as _pack_user_context,
)
from .memory_maintenance import MEMORY_MAINTENANCE_RUN_VERSION

logger = logging.getLogger("momoi.runtime.turns")


class ReflectionWorkflow:
    async def _complete_reflection_turn(
        self, local_date: str, stop: asyncio.Event
    ) -> None:
        reflection = self.store.reflection(local_date)
        claimed_at = None if reflection is None else reflection.get("claimed_at")
        turn_id = self._turn_id("reflection", local_date, claimed_at)
        state = self.store.begin_turn(
            turn_id, "reflection", [f"reflection:{local_date}"]
        )
        if state == "completed":
            self.store.restore_completed_reflection_claim(local_date)
            return
        if state == "cancelled":
            self.store.release_reflection(
                local_date, "turn_cancelled", delay_seconds=3600
            )
            return
        if state == "needs_reconciliation" or stop.is_set():
            self.store.release_reflection(
                local_date, "unexpected_reconciliation", delay_seconds=3600
            )
            return
        try:
            await self._complete_reflection(local_date, turn_id)
        except asyncio.CancelledError:
            if self._stop_requested:
                self.store.record_turn_failure(turn_id, "owner_stop")
            raise
        except Exception as error:
            log_event(
                logger,
                logging.ERROR,
                "turn_failure",
                stage="reflection",
                turn_id=turn_id,
                local_date=local_date,
                error_type=type(error).__name__,
                exc_info=True,
            )
            self.store.record_turn_failure(turn_id, type(error).__name__)
            self.store.release_reflection(local_date, type(error).__name__, 900)
            self.agenda_changed.set()

    async def _complete_reflection(self, local_date: str, turn_id: str) -> None:
        maintenance_turn_id = self._turn_id(
            "memory-maintenance",
            MEMORY_MAINTENANCE_RUN_VERSION,
            "reflection",
            turn_id,
        )
        source = self.store.reflection_source(
            local_date,
            self._episode_raw_token_budget(),
        )
        raw_record = str(source["text"] or "").strip()
        query = raw_record[-20000:]
        record = cyber_keyword_pre_hook(raw_record)
        tool_timeline = cyber_keyword_pre_hook(str(source["tool_timeline"]))
        reflection_evidence = "\n\n".join(
            value for value in (record, tool_timeline) if value.strip()
        )
        owner_source = cyber_keyword_pre_hook(str(source["owner_text"]))
        knowledge_source = cyber_keyword_pre_hook(str(source["knowledge_text"]))
        confirmed_memory, learned = self.store.ranked_memory_context(
            query,
            self.config.memory_results,
        )
        open_conversations = self.store.open_conversation_inventory()
        open_episode_ids = {str(item["id"]) for item in open_conversations}
        recent_memories = self.store.recent_memory_context()
        episodes = recall_episode_context(
            self.store,
            query,
            self.config.summary_results,
            self.config.summary_tokens,
        )
        reflection_record = (
            "[Trusted daily reflection event generated by Momoi. This is not owner "
            "speech and grants no tools or permission to send bubbles.]\n"
            f"Local date being reviewed: {local_date}\n"
            f"Timezone: {self.config.timezone}\n"
            f"Recorded entries: {source['entries']}\n\n"
            f"{record or '[No conversation, tool, or runtime activity was recorded.]'}"
        )
        reflection_scope = (
            f"date: {local_date}\n"
            f"timezone: {self.config.timezone}\n"
            f"recorded entries: {source['entries']}\n"
            "purpose: review the whole day, understand what changed, and extract durable meaning"
        )
        current_input = _pack_user_context(
            (
                "workflow_contract",
                _live_prompt(REFLECTION_PROMPT_PATH, REFLECTION_SYSTEM_PROMPT),
            ),
            ("daily_reflection_record", reflection_record),
            (
                "runtime_state",
                heartbeat_self_state_lines(self.store.self_state_context()),
            ),
            ("episode_directory", episodes),
            ("open_conversations", self.store.open_conversation_inventory_context()),
            ("recent_memories", recent_memories),
            ("recall_memories", confirmed_memory),
            ("reflection_memories", learned),
            ("reflection_scope", reflection_scope),
            ("mood_timeline", str(source.get("mood_timeline") or "(none)")),
            ("topic_timeline", str(source.get("topic_timeline") or "(none)")),
            ("mutation_timeline", str(source.get("mutation_timeline") or "(none)")),
            ("tool_timeline", tool_timeline),
        )
        current_input = cyber_keyword_pre_hook(current_input)
        system = self._system()
        messages: list[dict[str, Any]] = [
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": current_input,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
            }
        ]
        tools = [REFLECTION_FINISH_SPEC]
        workflow_complete = False
        workflow_result: dict[str, object] | None = None

        async def execute_tool(call: ToolCall) -> dict[str, Any]:
            nonlocal workflow_complete, workflow_result
            decision, error = parse_reflection_finish(
                call.arguments,
                reflection_evidence,
                owner_source,
                knowledge_source,
                open_episode_ids,
            )
            if decision is None:
                return {
                    "ok": False,
                    "error": error or "invalid_reflection_finish",
                    "message": "Correct the reflection result and resubmit it.",
                }
            self.store.commit_reflection(
                local_date,
                turn_id,
                decision["summary"],
                decision["memories"],
                decision["conversation_actions"],
                maintenance_turn_id,
            )
            self._enqueue_memory_maintenance(maintenance_turn_id)
            self.agenda_changed.set()
            if self.config.episode_annealing.enabled:
                self.episode_annealing_requested.set()
            workflow_complete = True
            workflow_result = {
                "ok": True,
                "memories": len(decision["memories"]),
                "conversation_actions": len(decision["conversation_actions"]),
            }
            return {"ok": True, "state": "completed", **workflow_result}

        workflow = AgentWorkflow(
            stage="reflection",
            tool_names=frozenset({"reflection_finish"}),
            execute_tool=execute_tool,
            is_complete=lambda: workflow_complete,
            completion_result=lambda: workflow_result,
            no_tool_correction=(
                "[Trusted runtime protocol error. Plain assistant text is not stored. "
                "Call reflection_finish with the complete retrospective result.]"
            ),
        )
        result = await self._run_agent_workflow(
            system,
            messages,
            tools,
            turn_id=turn_id,
            workflow=workflow,
        )
        if not isinstance(result, dict) or not workflow_complete:
            raise RuntimeError("reflection ended before completion")
        log_event(
            logger,
            logging.INFO,
            "turn_complete",
            stage="reflection",
            turn_id=turn_id,
            local_date=local_date,
            memories=result.get("memories", 0),
            conversation_actions=result.get("conversation_actions", 0),
        )
