from datetime import datetime
from typing import Any

from ...channel import Channel
from ...models import AgentReply, TurnDraft
from ..agent import TurnExecutionSpec
from ..context.current_state import pack_current_turn_context
from ..context.presentation import heartbeat_self_state_lines
from ..transcript.building import build_transcript
from ..transcript.rendering import render_messages
from ..turn_support import (
    WEBHOOK_PROMPT_PATH,
    WEBHOOK_SYSTEM_PROMPT,
    context_data_message as _context_data_message,
    live_prompt as _live_prompt,
)


class WebhookWorkflow:
    async def _complete_webhook_turn(
        self, prompt: str, turn_id: str, channel: Channel | None = None
    ) -> AgentReply:
        channel = channel or self.channel
        state = self.store.begin_turn(turn_id, "webhook", [turn_id])
        if state in {"completed", "cancelled", "needs_reconciliation"}:
            raise RuntimeError(f"webhook turn is {state}")
        long_term_memories = self.store.always_memory_context()
        conversation_rows = self._recent_conversation_rows()
        tool_activity = self.store.turn_activity(
            [str(row["turn_id"]) for row in conversation_rows]
        )
        transcript = build_transcript(
            conversation_rows,
            timezone=self.store.timezone,
            tool_activity=tool_activity,
        )
        transcript_messages = render_messages(
            [*transcript.orphaned, *transcript.groups],
            timezone=self.store.timezone,
            tool_activity=tool_activity,
        )
        recent_events = ", ".join(dict.fromkeys(
            f"E{message_id}"
            for group in (*transcript.orphaned, *transcript.groups)
            if group.role == "event"
            for message_id in group.message_ids
        ))
        self_state = self.store.self_state_context()
        runtime_state = heartbeat_self_state_lines(
            self_state,
            current_time=datetime.now(self.store.timezone).isoformat(timespec="seconds"),
        )
        current_input = pack_current_turn_context(
            self.store, "webhook",
            (
                "workflow_contract",
                _live_prompt(WEBHOOK_PROMPT_PATH, WEBHOOK_SYSTEM_PROMPT),
            ),
            ("current_webhook_task", prompt),
            (
                "runtime_directives",
                (
                    "[Trusted context generated by the runtime. This event task is "
                    "authorized only within the supplied Webhook tools; it is not a "
                    "statement from the owner.]\n"
                    "Available tools: curl for external data, send_bubbles for live beats, "
                    "and end_turn for terminal state."
                ),
            ),
            (
                "runtime_state",
                runtime_state,
            ),
            ("recent_events", recent_events),
        )
        system = self._system()
        context_message = _context_data_message(
            ("long_term_memories", long_term_memories),
            required=True,
        )
        assert context_message is not None
        messages: list[dict[str, Any]] = [
            context_message,
            *transcript_messages,
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": current_input,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
            },
        ]
        reply = await self._run_tool_loop(
            system,
            messages,
            self.tool_surface.conversation_specs(),
            [],
            TurnDraft(),
            execution=TurnExecutionSpec(
                "webhook",
                allowed_capabilities=frozenset({"read"}),
                permitted_tools=self.tool_surface.permitted_names("webhook"),
            ),
            source_event_id=turn_id,
            turn_id=turn_id,
            delivery_channel=channel,
        )
        if not isinstance(reply, AgentReply):
            raise RuntimeError("Webhook Turn ended without end_turn")
        return reply
