from datetime import datetime
import time
from typing import Any

from ...channel import Channel
from ...models import AgentReply, TurnDraft
from ..agent import TurnExecutionSpec
from ..context.current_state import pack_current_turn_context
from ..context.presentation import heartbeat_self_state_lines
from ..transcript.rendering import owner_idle_gap_message
from ..turn_support import (
    WEBHOOK_PROMPT_PATH,
    WEBHOOK_SYSTEM_PROMPT,
    live_prompt as _live_prompt,
)


class WebhookWorkflow:
    async def _complete_webhook_turn(
        self, prompt: str, turn_id: str, channel: Channel | None = None
    ) -> AgentReply:
        channel = channel or self.channel
        state = self.store.begin_turn(turn_id, "webhook", [turn_id])
        if state in {"completed", "cancelled", "needs_reconciliation"}:
            raise RuntimeError(f"webhook turn is {state}")
        shared = self.shared_turn_context(turn_id)
        conversation_rows = shared["rows"]
        transcript = shared["transcript"]
        transcript_messages = shared["history"]
        idle_gap = owner_idle_gap_message(
            conversation_rows,
            now=time.time(),
            timezone=self.store.timezone,
        )
        recent_events = ", ".join(dict.fromkeys(
            f"E{message_id}"
            for group in (*transcript.orphaned, *transcript.groups)
            if group.role == "event"
            for message_id in group.message_ids
        ))
        self_state = self.store.self_state_context()
        self_state = heartbeat_self_state_lines(
            self_state,
            current_time=datetime.now(self.store.timezone).isoformat(timespec="seconds"),
        )
        current_input = pack_current_turn_context(
            self.store, "webhook",
            ("scoped_memories", self.store.scoped_memory_context("webhook")),
            (
                "workflow_contract",
                _live_prompt(WEBHOOK_PROMPT_PATH, WEBHOOK_SYSTEM_PROMPT),
            ),
            ("current_webhook_task", prompt),
            (
                "runtime_directives",
                (
                    "[Trusted context generated by the runtime. This event task is "
                    "authorized only within the supplied Webhook tools; it is not a "
                    "statement from the owner.]\n"
                    "Available tools: web_fetch for external data, reply for live replies, "
                    "and end_turn for terminal state."
                ),
            ),
            (
                "self_state",
                self_state,
            ),
            ("recent_events", recent_events),
        )
        system = self._system(planner=True)
        messages: list[dict[str, Any]] = [
            *shared["messages"],
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": current_input + ("\n\n" + "\n".join(block["text"] for block in idle_gap["content"] if block.get("type") == "text") if idle_gap else ""),
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
            },
        ]
        reply = await self._run_tool_loop(
            system,
            messages,
            self.tool_surface.conversation_specs(),
            [],
            TurnDraft(),
            execution=TurnExecutionSpec(
                "webhook",
                allowed_capabilities=frozenset({"read"}),
                permitted_tools=self.tool_surface.permitted_names("webhook"),
            ),
            source_event_id=turn_id,
            turn_id=turn_id,
            delivery_channel=channel,
        )
        if not isinstance(reply, AgentReply):
            raise RuntimeError("Webhook Turn ended without end_turn")
        return reply
